# Generated by Django 4.1 on 2023-08-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yektanet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('code', models.TextField()),
            ],
        ),
    ]
